"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ArrowUpRight, Menu, Phone, X } from "./icons";

const nav = [{ href: "/san-pham", label: "Sản phẩm" }, { href: "/giai-phap", label: "Giải pháp" }, { href: "/gioi-thieu", label: "Về Golden Core" }, { href: "/tin-tuc", label: "Góc kiến thức" }];
export function Brand() { return <Link href="/" className="brand" aria-label="Golden Core - Trang chủ"><span className="brand-mark"><i/><i/><i/></span><span>GOLDEN <b>CORE</b></span></Link>; }
export function Header() { const [open, setOpen] = useState(false); const path = usePathname(); return <><header className="site-header"><div className="header-inner wrap"><Brand /><nav className="desktop-nav">{nav.map(n => <Link className={path.startsWith(n.href) ? "active" : ""} href={n.href} key={n.href}>{n.label}</Link>)}</nav><div className="header-cta"><Link className="header-phone" href="tel:0941495982"><Phone size={16}/> <span>0941 495 982</span></Link><Link className="mini-quote" href="/bao-gia">Báo giá <ArrowUpRight size={15}/></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Mở menu" aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></div></header>{open && <div className="mobile-menu"><div className="wrap">{nav.map(n => <Link onClick={() => setOpen(false)} href={n.href} key={n.href}>{n.label}<ArrowUpRight /></Link>)}<Link onClick={() => setOpen(false)} className="button gold" href="/bao-gia">Yêu cầu báo giá <ArrowUpRight /></Link></div></div>}</>; }
export function Footer() { return <footer><div className="wrap footer-top"><div><Brand /><p className="footer-blurb">Nền tảng vững cho những hành trình vận hành hiệu quả hơn.</p></div><div><p className="footer-label">KHÁM PHÁ</p><Link href="/san-pham">Sản phẩm</Link><Link href="/giai-phap">Giải pháp</Link><Link href="/tin-tuc">Góc kiến thức</Link></div><div><p className="footer-label">LIÊN HỆ</p><a href="tel:0941495982">0941 495 982</a><a href="mailto:goldencore.biz@gmail.com">goldencore.biz@gmail.com</a><span><b>Văn phòng:</b> Số 59, Đường Tỉnh 418-UBND,<br/>Thôn Tây Ninh, Xã Đoài Phương, Hà Nội</span><span><b>Kho hàng:</b> Đường 376, Xã Nguyễn Văn Linh, Hưng Yên</span></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Golden Core. Bảo lưu mọi quyền.</span></div></footer>; }
